### ISSUE TITLE
Occasional "java.lang.NullPointerException" errors

### ISSUE THREAD

**Issue by subvertallchris** [graphaware/neo4j-timetree#14]
This is sort of a weird one so I apologize in advance if it's a little unclear.

We're finding that under certain conditions, queries for ranges with hour resolution fail. We get an error from Jetty:

```
<h2>HTTP ERROR: 500</h2>
       <p>Problem accessing /graphaware/timetree/range/1423494497000/1424099297000. Reason:
       <pre>    java.lang.NullPointerException</pre></p>
       <hr /><i><small>Powered by Jetty://</small></i>
```

It seems like it only happens under hour resolution and if the older date timestamp greatly exceeds the existing nodes within the graph. So, in the query above, if I adjust the start timestamp up to within a day or so where we actually have data, it'll work. Even stranger is that after I get it working, I can start going back further and things will just work normally, it'll create the missing nodes as I go. As a result, I don't see this problem locally but our CI server complains since it sets up a new DB every time.

For now, we're working around it in the app. We look at what the user requests and if it falls outside of our bounds, we correct it. It does seem like a weird issue, though, so I thought I'd point it out.

**Comment by bachmanm** [comment]
Hey Chris,

could you look into the log and see if there's a full stack trace? Thanks!

**Comment by subvertallchris** [comment]
How's this?

```
WARN  c.g.module.timetree.api.TimeTreeApi - Bad Request: startTime must be less than endTime
java.lang.IllegalArgumentException: startTime must be less than endTime
	at com.graphaware.module.timetree.domain.ValidationUtils.validateRange(ValidationUtils.java:17) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.domain.TimeInstant.getInstants(TimeInstant.java:155) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstants(SingleTimeTree.java:133) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.api.TimeTreeApi.getInstants(TimeTreeApi.java:84) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) [javax.servlet-3.0.0.v201112011016.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

**Comment by subvertallchris** [comment]
Shit, the one I just posted was when we screwed up. :-) Gimme a minute...

**Comment by bachmanm** [comment]
that would be great.. would give me a starting point for investigating and trying to reproduce in a unit test

**Comment by iumehara** [comment]
```
WARN  o.e.jetty.servlet.ServletHandler - 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

**Comment by subvertallchris** [comment]
That's from my co-worker's machine where we were experiencing it.

**Comment by bachmanm** [comment]
unfortunately, this doesn't actually show the stacktrace I need :( Anything in data/graph.db/messages.log? When does it happen, under concurrent load? Any sample data or reproducible test case that could be provided? Thanks a lot, M.

**Comment by subvertallchris** [comment]
Bummer. I'll check that out on his machine.

This happens usually on a reasonably fresh DB after adding some data to it. We're just running tests against it, nothing in production yet. Sadly, not much I can really provide in the way of sample data. :-( I'll have to play with it more and see if I can get you more info. Sorry for the lack of details here.

Incidentally, this revealed that limiting the bounds of the query is a good thing to do within our app, anyway. It might be nice if there was an option to set the max start/end dates to prevent the creation of thousands of extra nodes within the plugin. Just now, I accidentally did an hourly query directly against the GraphAware endpoint that resulted in 11k new nodes.

**Comment by subvertallchris** [comment]
I'm having a little trouble getting messages.log setup to find this error. Logging `com.graphaware` doesn't get it, neither does `org.neo4j`. What do you think?

**Comment by bachmanm** [comment]
Could you try to add the following to conf/custom-logback.xml, then reproduce the error and look at extensions.log?

    <appender name="EXTENSIONLOG"  class="ch.qos.logback.core.FileAppender">
      <file>data/log/extensions.log</file>
      <encoder>
          <pattern>%date{yyyy-MM-dd HH:mm:ss.SSSZ} %-5level [%logger{15}]: %message%n</pattern>
      </encoder>
    </appender>

    <logger name="com.mycompany" level="debug">
      <appender-ref ref="EXTENSIONLOG"/>
    </logger>

**Comment by subvertallchris** [comment]
Sure, five minutes...

**Comment by subvertallchris** [comment]
OK, did it, but it's not logging the error to it. Since the error is coming from Jetty, do we need to log that?

**Comment by subvertallchris** [comment]
How bout this? It starts the same as what I posted before but continues to reference lines from the extension.

```
2015-02-16 17:33:46.412-0500 WARN  [o.e.j.s.ServletHandler]: 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
Caused by: java.lang.NullPointerException: null
	at com.graphaware.module.timetree.SingleTimeTree.createChild(SingleTimeTree.java:496) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.createFirstChildEver(SingleTimeTree.java:423) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.findOrCreateChild(SingleTimeTree.java:363) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstant(SingleTimeTree.java:286) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstant(SingleTimeTree.java:289) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstant(SingleTimeTree.java:289) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstant(SingleTimeTree.java:289) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstant(SingleTimeTree.java:118) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.SingleTimeTree.getOrCreateInstants(SingleTimeTree.java:134) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at com.graphaware.module.timetree.api.TimeTreeApi.getInstants(TimeTreeApi.java:84) ~[graphaware-timetree-2.1.7.28.19.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) ~[graphaware-server-enterprise-all-2.1.7.28.jar:na]
	... 21 common frames omitted
```

**Comment by bachmanm** [comment]
perfect, thx!

**Comment by bachmanm** [comment]
I'm looking and looking, but can't see it. Any chance you could send a test snippet by email? The thing that fails in CI. I'll have a look again tomorrow, no luck today. But it definitely is a bug.

**Comment by subvertallchris** [comment]
Are you trying it with a fresh db? I find that something always happens to fix it, then it doesn't come back. It's definitely only the hourly resolution, which is weird.

I'll see if I can recreate the problem in a sample repo tonight.

**Comment by subvertallchris** [comment]
I'm having trouble reproducing it in a sample app but I am able to consistently reproduce it in our app's specs. I've been able to piece together a little more information about it:

If I run the entire test file, it crashes with the error. If I run only the tests that fail, it does not. This leads me to believe that it has something to do with a cleanup operation in the test before it OR some interaction between the preceding test's cleanup and the failing tests' setup... but I can't say where or why.

I've found that if I interrupt the tests before the failing query takes place, the problem is still present after a restart of Neo4j. I can't share the code but I might be able to share my DB since it only contains sample data. Would that help?

Could this be some kind of race condition? Maybe an index returns a node ID that no longer exists?

**Comment by bachmanm** [comment]
The DB that causes the test to fail would definitely help. I think I know what causes it - two child nodes that should be linked with NEXT relationship are not linked. But I have no idea how it gets to that state.

How are you cleaning up the database?

**Comment by subvertallchris** [comment]
I'll see if that can be arranged when I get into the office. Shouldn't be a
problem.

We're doing a basic "MATCH (n) OPTIONAL MATCH (n)-[r]->() DELETE n, r".

**Comment by bachmanm** [comment]
What it could be in that case is that the database isn't entirely cleaned up before another test starts...

**Comment by subvertallchris** [comment]
Yup, that is what it looks like. If I run one more cleanup of the DB before this round of tests starts, that does prevent it! I guess now the question is just why.

**Comment by bachmanm** [comment]
Fixed with https://github.com/graphaware/neo4j-timetree/commit/dd07ce2b777a566eccd97e2c7b4e6b4f5d7c44e5 (which I incorrectly referenced as #16). Part of 2.1.7.28.20, which has just been released
