### ISSUE TITLE
A RequestDispatcher could not be located for the default servlet 'default'

### ISSUE THREAD

**Issue by dangerginger** [graphaware/neo4j-timetree#64]
I am trying to add `graphaware/neo4j/timetree` to my project, but I am getting this error: `org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'default'`

neo4j/plugins folder
```
total 26M
-rw-r--r-- 1 admin admin 13M Jan  1 10:11 graphaware-server-community-all-3.1.0.44.jar
-rw-r--r-- 1 admin admin 13M Jan  1 10:11 graphaware-timetree-3.1.0.44.26.jar
```

I added this to my neo4j.conf: `dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware`

The response from postman to `POST http://localhost:7474/graphaware/timetree/now` has a 500 status code with the error above: 

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /graphaware/timetree/now. Reason:
<pre>    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'default'</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

**Comment by dangerginger** [comment]
I should have mentioned I am running neo4j community v3.1.0.

**Comment by ikwattro** [comment]
Hi @dangerginger 

Unfortunately I'm unable to reproduce the issue : 

```bash
ikwattro@graphaware-team ~/d/_/310> ll plugins/
total 27056
-rw-r--r--  1 ikwattro  staff    13M Dec 16 10:09 graphaware-server-enterprise-all-3.1.0.44.jar
-rw-r--r--  1 ikwattro  staff   685K Dec 16 10:09 graphaware-timetree-3.1.0.44.26.jar
ikwattro@graphaware-team ~/d/_/310>
```

Auth disabled : 

```bash
ikwattro@graphaware-team ~> http POST "http://localhost:7474/graphaware/timetree/now"
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Sun, 01 Jan 2017 23:49:06 GMT
Server: Jetty(9.2.9.v20150224)
Transfer-Encoding: chunked

{
    "id": 3,
    "labels": [
        "Day"
    ],
    "properties": {
        "value": 1
    }
}
```

Auth enabled : 

```bash
ikwattro@graphaware-team ~> http -a neo4j:password POST "http://localhost:7474/graphaware/timetree/now"
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Sun, 01 Jan 2017 23:52:34 GMT
Server: Jetty(9.2.9.v20150224)
Transfer-Encoding: chunked

{
    "id": 3,
    "labels": [
        "Day"
    ],
    "properties": {
        "value": 1
    }
}
```

Can you paste the stacktrace from neo4j.log and debug.log. Thanks

**Comment by dangerginger** [comment]
plugins dir
```
┌─[admin@home]─[~/neo4j-community-3.1.0/plugins]
└──╼ ll
total 26M
-rw-r--r-- 1 admin admin 13M Jan  1 10:11 graphaware-server-community-all-3.1.0.44.jar
-rw-r--r-- 1 admin admin 13M Jan  1 10:11 graphaware-timetree-3.1.0.44.26.jar
```

neo4j.log
```2017-01-01 23:56:38.447+0000 WARN   Request processing failed; nested exception is java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'default'
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'default'
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:122)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.graphaware.server.tx.LongRunningTransactionFilter.doFilter(LongRunningTransactionFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.graphaware.server.foundation.bootstrap.GraphAwareBootstrappingFilter.doFilter(GraphAwareBootstrappingFilter.java:85)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: A RequestDispatcher could not be located for the default servlet 'default'
        at org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler.handleRequest(DefaultServletHttpRequestHandler.java:119)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        ... 30 more
```

**Comment by dangerginger** [comment]
There is nothing in the debug.log.

Attempting the to call the Cypher procedure in the browser and on the cli neo4j-shell give the following error:
```
WARNING: There is no procedure with the name `ga.timetree.now` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```

That seems to clear up the problem, but I am not sure how I installed it incorrectly.

**Comment by dangerginger** [comment]
Ok, very sorry to have taken your time.  Somehow both of the files I placed in the plugin directory are exactly the same.  I somehow screwed up copying them.  I'm not sure what I did but it was easy to fix.  I replaced the timetree jar file and it works just fine.  I wish I would have figured this out in a less public forum lol.

**Comment by ikwattro** [comment]
No worries, glad it works now
