### ISSUE TITLE
ClassNotFound org.joda.time.DateTimeFieldType

### ISSUE THREAD

**Issue by MeadBarrel** [graphaware/neo4j-timetree#81]
I'm trying to set up timetrees, but keep getting this 

```
2020-02-21 11:45:19.996+0000 INFO  ======== Neo4j 3.5.12 ========
2020-02-21 11:45:20.013+0000 INFO  Starting...
2020-02-21 11:45:24.037+0000 INFO  GraphAware Runtime enabled, bootstrapping...
2020-02-21 11:45:24.068+0000 INFO  Bootstrapping module with order 1, ID TT, using com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
2020-02-21 11:45:24.355+0000 INFO  Shutting down GraphAware Runtime...
2020-02-21 11:45:24.355+0000 INFO  Terminating task scheduler...
2020-02-21 11:45:24.355+0000 INFO  Task scheduler terminated successfully.
2020-02-21 11:45:24.356+0000 INFO  GraphAware Runtime shut down.
2020-02-21 11:45:24.367+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5972d253' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5972d253' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5972d253' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5972d253' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@29314cc9' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
        ... 9 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@6a84bc2a' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:459)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@6a84bc2a' was successfully initialized, but failed to start. Please see the attached cause exception "org.joda.time.DateTimeFieldType".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/joda/time/DateTimeFieldType
        at com.graphaware.module.timetree.domain.Resolution.<clinit>(Resolution.java:32)
        at com.graphaware.module.timetree.module.TimeTreeConfiguration.<clinit>(TimeTreeConfiguration.java:38)
        at com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper.defaultConfiguration(TimeTreeModuleBootstrapper.java:52)
        at com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper.defaultConfiguration(TimeTreeModuleBootstrapper.java:37)
        at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:60)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
        at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: org.joda.time.DateTimeFieldType
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 30 more
2020-02-21 11:45:24.369+0000 INFO  Neo4j Server shutdown initiated by request
```

I have added the following to my neo4j config:

```
dbms.security.procedures.unrestricted=ga.timetree.*,apoc.*

#For the framework to work at all, you need this
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware

# Runtime must be enabled like this
com.graphaware.runtime.enabled=true

# A Runtime module that takes care of attaching the events like this (TT is the ID of the module)
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

# autoAttach must be set to true
com.graphaware.module.TT.autoAttach=true

# Optionally, nodes which represent events and should be attached automatically have to be defined (defaults to nodes with label Event)
com.graphaware.module.TT.event=hasLabel('Email')

# Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
com.graphaware.module.TT.timestamp=time

# Optionally, a property on the event nodes that represents the node ID (long) of the root node for the tree, to which the event should be attached (defaults to "timeTreeRootId")
com.graphaware.module.TT.customTimeTreeRootProperty=rootId

# Optionally, a resolution can be specified (defaults to DAY)
com.graphaware.module.TT.resolution=HOUR

# Optionally, a time zone can be specified (defaults to UTC)
com.graphaware.module.TT.timezone=GMT+1

# Optionally, a relationship type with which the events will be attached to the tree can be specified (defaults to AT_TIME)
com.graphaware.module.TT.relationship=SENT_ON

# Optionally, a relationship direction (from the tree's point of view), with which the events will be attached to the tree can be specified (defaults to INCOMING)
com.graphaware.module.TT.direction=INCOMING
```

And have 3.5.12 .jar files for timeseries and framework in my plugins folder. Any advice?

**Comment by MeadBarrel** [comment]
Actually, i dropped joda-time jar into the lib folder and it worked
